## [출석인정용과제]
Building_Permits.csv를 dataframe 형태로 읽어들여 sfPermits에 집어 넣고 그 dataframe의 행과 열의 갯수를 출력하시오

In [1]:
import numpy as np 
import pandas as pd 

sfPermits = pd.read_csv("Building_Permits.csv")

print(sfPermits.shape)
sfPermits

C:\Users\user\anaconda3\envs\myR\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (22,32) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(198900, 43)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,NaN,Bush,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,NaN,Indiana,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,NaN,Sutter,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489796283803

## [학점취득용과제 1]

sfPermits의 column별로 null인 data의 갯수를 구해 missingCount에 집어넣고 missingCount의 type을 출력하시오. 그 후 missingCount를 null인 data의 갯수의 내림차순으로 정렬하여 상위 10개만 출력하시오

In [2]:
missingCount = sfPermits.isnull().sum()
missingCount.dtypes
missingCount.sort_values(ascending=False)

TIDF Compliance                           198898
Voluntary Soft-Story Retrofit             198865
Unit Suffix                               196939
Street Number Suffix                      196684
Site Permit                               193541
Structural Notification                   191978
Fire Only Permit                          180073
Unit                                      169421
Completed Date                            101709
Permit Expiration Date                     51880
Existing Units                             51538
Proposed Units                             50911
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Number of Proposed Stories                 42868
Number of Existing Stories                 42784
Proposed Use                               42439
Existing Use                               41114
Estimated Cost                             38066
Plansets                                   37309
First Construction Document Date           14946
Issued Date                                14940
Revised Cost                                6066
Street Suffix                               2768
Neighborhoods - Analysis Boundaries         1725
Supervisor District                         1717
Zipcode                                     1716
Location                                    1700
Description                                  290
Lot                                            0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Record ID                                      0
Street Number                                  0
Street Name                                    0
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Permit Number                                  0
dtype: int64

## [학점취득용과제 2]

위 문제에서 구한 column별 null data의 갯수 중에는 중복된 값도 있고 유일한 값도 있는데 이 중 유일한 값이 몇개나 있는지 구해서 출력하시오. value_counts()라는 method를 활용하고 아마 배우지 않은 method를 자신이 직접 찾아내어 사용해야 할 수도 있음. <br>
**한 줄의 코드로 작성 가능함.**

In [7]:
missingCount.drop_duplicates(keep=False).value_counts().shape[0]

27